import type { Metadata } from "next";
import NavigationBar from "@/ui/NavigationBar";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";


const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
      <html lang="en" className={`${spaceGrotesk.variable} h-full antialiased`}>
      <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>Vannaroth Ngoc</title>
      </head>
      <body className="min-h-full flex flex-col mx-auto max-w-360">
        <NavigationBar />
        {children}
      </body>
      </html>
  );
}
